import type { Lang } from "./types";

/**
 * Researched artist biographies.
 *
 * The project's content rule applies here more sharply than anywhere else: these are
 * real, living people. A plausible-sounding bio assembled from a model's memory gets
 * nationalities, labels and dates wrong, and being wrong about a person in public is a
 * different class of mistake from being wrong about a ticket price. So every entry is
 * researched from a citable source and carries it in `sources`; an artist we could not
 * verify simply has no entry, and their page keeps showing dates without a bio — the
 * same way an event with no announced line-up says so rather than inventing one.
 *
 * `bio` is two to four sentences, French first (the source of truth) and English for
 * `/en`. Facts only: where they are from, what they play, what they are known for.
 * No superlatives we cannot source, no "one of the most influential artists of his
 * generation" — that sentence is true of nobody and printable about everybody.
 */
export interface ArtistBio {
  /** Matches `Artist.slug` from lib/artists.ts (i.e. `slugify(name)`). */
  slug: string;
  bio: { fr: string; en: string };
  /** Country or city the artist is from, as stated by the source. */
  origin?: string;
  /** Year they started releasing/performing, when a source gives one. */
  since?: number;
  /** Labels, when documented — a strong relevance signal for the genre pages. */
  labels?: string[];
  /** URLs the facts came from. Never empty: no source, no entry. */
  sources: string[];
  /**
   * Avatar, and the credit that legally has to travel with it.
   *
   * Sourced from Wikimedia Commons only. A press-kit or Instagram shot is a
   * copyrighted work whoever publishes it, and "press use" is not a licence to
   * illustrate a directory. Commons states its terms, and most of its photos are
   * CC BY / CC BY-SA — which permit reuse *provided* the author and licence are
   * shown. Hence `credit`: it is not decoration, it is the condition of use, and
   * `ArtistPage` renders it under the portrait.
   */
  photo?: {
    /** Local file under /artists/, produced by .research/artists/avatars.py. */
    file: string;
    /** Author / credit line exactly as Commons states it. */
    author: string;
    /** Licence short name, e.g. "CC BY-SA 4.0". */
    license: string;
    /** Commons file page, so a reader can check the terms themselves. */
    page: string;
  };
}

/* BIOS:start — generated by .research/artists/ingest.py, do not edit by hand */
export const BIOS: Record<string, ArtistBio> = {};
/* BIOS:end */

export const bioFor = (slug: string): ArtistBio | undefined => BIOS[slug];

export const bioText = (b: ArtistBio, lang: Lang): string => (lang === "fr" ? b.bio.fr : b.bio.en);

/** How many artist pages currently carry a researched bio — used by the audit script. */
export const BIO_COUNT = Object.keys(BIOS).length;
