import type { RaveEvent } from "./types";
import { EVENTS, PHOTOS, imageUrl, rankGenres, slugify, upcoming, upcomingFirst } from "./data";

/**
 * Les organisateurs : la marque derrière une soirée.
 *
 * Le catalogue savait dire *où* (`/lieux/{slug}`), *qui joue* (`/artistes/{slug}`) et
 * *quoi* (`/genres/{slug}`), jamais *qui programme*. C'est pourtant une intention de
 * recherche à part entière (« teletech manchester », « awakenings agenda », « hangar
 * festival »), et la seule qui relie des dates que rien d'autre ne rassemble : une
 * marque de club qui sort de ses murs, un collectif qui tourne de ville en ville, un
 * promoteur de festival qui tient trois éditions dans trois pays.
 *
 * ## Une salle n'est pas un organisateur, et la frontière décide de l'existence de la page
 *
 * Publier `/organisateurs/fuse` à côté de `/lieux/fuse` mettrait deux pages du site en
 * concurrence sur la même requête, avec le même agenda dessous : exactement ce que le
 * dépôt refuse ailleurs (le pays écrit de deux façons, la ville en deux orthographes,
 * les pages `/show/` retirées pour quasi-doublon). D'où la règle de `build()` : une
 * marque n'a de page que si sa programmation **déborde d'un seul lieu**, c'est-à-dire
 * au moins deux salles ou au moins deux villes. En dessous, la fiche de salle répond
 * déjà et mieux, puisqu'elle porte l'adresse et la carte.
 *
 * ## La correspondance se fait sur des mots entiers, jamais sur une sous-chaîne
 *
 * C'est la règle d'`eventsForPlace()` (« Ain » est une sous-chaîne de « Saintes »),
 * repayée ici sur des noms courts : « Fuse » est dans « Fusebox », « Index » dans
 * « Indexation ». Le titre est découpé en mots par `slugify()`, et un libellé de
 * `match` doit s'y retrouver comme **suite de mots consécutifs**.
 *
 * `venues` est la seconde porte, pour les marques dont le titre ne porte pas le nom
 * (une nuit au Fuse s'appelle rarement « Fuse »). Elle ne se pose que sur une salle
 * dont **toute** la programmation est celle de la marque, sinon on revendique les
 * soirées d'un promoteur invité, ce qui est pire que ne rien revendiquer.
 *
 * Le contenu de `PROMOTERS` est écrit par `python3 .research/promoters/ingest.py`
 * entre les marqueurs `PROMOTERS:start/end`. Ne pas éditer la map à la main.
 */
export type PromoterKind = "collectif" | "organisateur" | "club" | "label";

export interface Promoter {
  slug: string;
  name: string;
  kind: PromoterKind;
  /** Ville d'attache, telle que la source officielle la donne. */
  city: string;
  /** Clé de pays du catalogue (`UK`, jamais `United Kingdom`). */
  country: string;
  /** Année de création, seulement quand une source la donne. */
  since?: number;
  /** Présentation en français, source de vérité. */
  desc: string;
  /** Présentation anglaise ; à défaut, `/en` retombe sur le français. */
  descEn?: string;
  site?: string;
  instagram?: string;
  /** Les libellés qui identifient la marque dans le titre d'un événement. */
  match: string[];
  /** Les salles dont toute la programmation est celle de la marque. */
  venues?: string[];
  /**
   * Les pays où la marque programme, quand son nom est un mot courant.
   *
   * « Circus » attrapait « David Guetta presents Galactic Circus » à Ibiza : le mot
   * est dans le titre, la soirée n'a rien à voir. Restreindre aux pays où la marque
   * tourne referme la porte sans toucher aux marques qui voyagent vraiment, Teletech
   * jouant bien en Finlande et en Suisse.
   */
  countries?: string[];
  /**
   * Les titres à écarter malgré une correspondance.
   *
   * Dernier recours pour un homonyme isolé qu'aucun pays ne sépare : une soirée
   * *invitant* la marque n'est pas une soirée *de* la marque, et se l'attribuer
   * revendique le travail d'un autre promoteur.
   */
  exclude?: string[];
}

/* PROMOTERS:start */
const RAW: Promoter[] = [
  { slug: "afta-dark", name: "AFTA DARK", kind: "organisateur", city: "Birmingham", country: "UK", desc: "AFTA DARK est une série de soirées after hebdomadaire née au LAB11 de Birmingham, sur une programmation house, minimal et tech house. En septembre 2026 la marque a déplacé son rendez-vous du samedi à Nottingham, au Secret Vault, où elle tourne de 22 h 30 à 3 h 30 avec des DJs locaux et invités. Elle continue en parallèle de programmer Birmingham.", descEn: "AFTA DARK is a weekly after hours series that made its name at LAB11 in Birmingham, built on house, minimal and tech house. In September 2026 the brand moved its Saturday night to Nottingham's Secret Vault, running 10.30pm to 3.30am with local and guest DJs. It still books Birmingham alongside it.", site: "https://www.afta-dark.com/", match: ["afta dark"] },
  { slug: "astropolis", name: "Astropolis", kind: "organisateur", city: "Brest", country: "France", since: 1995, desc: "Né à l'été 1995 dans le Nord-Finistère, Astropolis est le plus ancien festival de musiques électroniques encore en activité en France. Rave éphémère devenue festival urbain, il investit chaque été le Manoir de Keroual et les salles de Brest, et prolonge l'année par ses formats Astroclub et Cabaret Sonique.", descEn: "Born in the summer of 1995 in northern Finistere, Astropolis is the oldest electronic music festival still running in France. Once a one-off rave, now a city-wide festival, it takes over the Manoir de Keroual and Brest's venues every summer and carries on year-round through its Astroclub and Cabaret Sonique nights.", site: "https://astropolis.org/", instagram: "https://www.instagram.com/astropolis", match: ["astropolis", "astroclub", "cabaret sonique"] },
  { slug: "awakenings", name: "Awakenings", kind: "organisateur", city: "Amsterdam", country: "Netherlands", since: 1997, desc: "Awakenings organise des soirées et des festivals techno aux Pays-Bas depuis 1997, année de sa première nuit à la Gashouder d'Amsterdam. La marque fait aujourd'hui tourner un festival d'été à Hilvarenbeek, l'édition Upclose à Spaarnwoude et une semaine de dates pendant l'Amsterdam Dance Event. Elle annonce plus de 300 000 visiteurs par an.", descEn: "Awakenings has been putting on techno parties and festivals in the Netherlands since 1997, the year of its first night at Amsterdam's Gashouder. The brand now runs a summer festival in Hilvarenbeek, the Upclose edition at Spaarnwoude and a week of dates during Amsterdam Dance Event. It reports more than 300,000 visitors a year.", site: "https://www.awakenings.com/", instagram: "https://www.instagram.com/awakenings", match: ["awakenings"] },
  { slug: "basis", name: "BASIS", kind: "club", city: "Utrecht", country: "Netherlands", desc: "BASIS est un club techno du centre d'Utrecht, installé dans une cave voisine du vieux canal, qui se présente sous le mot d'ordre « Back to the BASIS » et revendique plus de dix ans d'activité. La cabine est montée à 360 degrés, au même niveau que le public, et le système son est un VOID. Le club sort de ses murs pour son BASIS Outdoor, monté au Beton-T.", descEn: "BASIS is a techno club in the centre of Utrecht, in a basement next to the old canal, running under the motto \"Back to the BASIS\" and claiming more than ten years of activity. The booth is a 360 degree setup on the same level as the crowd, with a VOID sound system. The club steps outside its walls for BASIS Outdoor, held at Beton-T.", site: "https://clubbasis.nl/", instagram: "https://www.instagram.com/clubbasis", match: ["basis"], countries: ["Netherlands"], venues: ["BASIS, Oudegracht aan de Werf 97"] },
  { slug: "blacklist", name: "Blacklist", kind: "organisateur", city: "Cologne", country: "Germany", desc: "Blacklist est un festival de musiques bass monté à la Turbinenhalle d'Oberhausen, qui se présente comme le premier rendez-vous bass d'Allemagne, du dubstep à la drum and bass. La marque appartient à Bootshaus Live GmbH, à Cologne, et prolonge son festival par des dates au Bootshaus.", descEn: "Blacklist is a bass music festival held at the Turbinenhalle in Oberhausen, presenting itself as Germany's leading bass event, from dubstep through to drum and bass. The brand belongs to Bootshaus Live GmbH in Cologne and extends its festival with dates at the Bootshaus.", site: "https://www.blacklist-festival.com/", instagram: "https://www.instagram.com/blacklist_crew", match: ["blacklist"] },
  { slug: "bloom", name: "Bloom", kind: "organisateur", city: "Porto", country: "Portugal", desc: "Bloom est l'organisateur portuense qui tient le Bloom Festival sur la piste de l'aérodrome de Maia, les 18 et 19 septembre. Sous la même marque, il programme aussi hors du festival, avec Bloom & Maz pour Halloween à Porto et une nuit avec le collectif Monkey Project au Pátio da Galé, à Lisbonne. Sa programmation va de la house au tech house.", descEn: "Bloom is the Porto promoter behind Bloom Festival, held on the runway of the Maia aerodrome on 18 and 19 September. Under the same name it also programmes outside the festival, with Bloom & Maz for Halloween in Porto and a night with the Monkey Project collective at Pátio da Galé in Lisbon. Its bill runs from house to tech house.", site: "https://bloomfest.pt/", instagram: "https://www.instagram.com/bloomfest.pt", match: ["bloom"], countries: ["Portugal"] },
  { slug: "bootshaus", name: "Bootshaus", kind: "club", city: "Cologne", country: "Germany", since: 2004, desc: "Le Bootshaus est un club de Cologne né en 2004 sur les quais de Deutz, héritier du Warehouse ouvert en 1991, l'un des premiers lieux techno d'Allemagne. Il s'est fait connaître par sa série Loonyland et programme aujourd'hui aussi bien l'EDM que la hard techno, le hardstyle et la drum and bass sur trois salles. Il est exploité par Bootshaus Cologne GmbH et emmène sa marque hors du club, par exemple pour ses soirées sur un bateau du Rhin.", descEn: "Bootshaus is a Cologne club that opened in 2004 on the Deutz waterfront, heir to the Warehouse that opened in 1991 as one of Germany's first techno venues. It made its name with the Loonyland party series and now books EDM as readily as hard techno, hardstyle and drum and bass across three rooms. It is run by Bootshaus Cologne GmbH and takes its brand outside the club, for instance for its parties on a Rhine boat.", site: "https://www.bootshaus.tv/", instagram: "https://www.instagram.com/bootshaus", match: ["bootshaus"], venues: ["Bootshaus"] },
  { slug: "brunch-electronik", name: "Brunch Electronik", kind: "organisateur", city: "Barcelona", country: "Spain", desc: "Brunch Electronik est née à Barcelone d'une série de petites fêtes de plein air du dimanche après-midi, fondée par Loïc Le Joliff. Le format s'est étendu à d'autres villes, dont Lisbonne, l'Algarve et l'Andorre, chacune avec son propre site. Son rendez-vous barcelonais a pris la forme d'un festival de trois jours au Parc del Fòrum.", descEn: "Brunch Electronik grew out of a series of small Sunday afternoon open-air parties in Barcelona, founded by Loïc Le Joliff. The format has spread to other cities, including Lisbon, the Algarve and Andorra, each with its own site. Its Barcelona date has grown into a three-day festival at Parc del Fòrum.", site: "https://barcelona.brunchelectronik.com/", instagram: "https://www.instagram.com/brunchbcn", match: ["brunch electronik"] },
  { slug: "butan", name: "Butan", kind: "collectif", city: "Wuppertal", country: "Germany", desc: "Butan est une marque de soirées techno et rave de Wuppertal, héritière du club du même nom, qui programme aujourd'hui dans plusieurs salles de la ville plutôt que dans un lieu à elle. Son site annonce ses dates au Relikt et à l'U-Club, avec un appel à candidatures ouvert aux DJ pour ses prochaines soirées.", descEn: "Butan is a techno and rave party brand from Wuppertal, heir to the club of the same name, which now books across several rooms in the city rather than one venue of its own. Its site lists its dates at Relikt and the U-Club, with an open call for DJs to play its coming nights.", site: "https://butan-club.de/", instagram: "https://www.instagram.com/butanclubofficial", match: ["butan"], countries: ["Germany"] },
  { slug: "c12", name: "C12", kind: "club", city: "Brussels", country: "Belgium", since: 2018, desc: "Ouvert le 2 février 2018 dans la galerie Horta, sous la gare centrale de Bruxelles, C12 est une plateforme pluridisciplinaire lancée par le collectif Deep in House. Mille places, house et techno, mais aussi installations, expositions et soirées invitées sous l'intitulé « C12 Nite ».", descEn: "Opened on 2 February 2018 in the Horta Gallery, beneath Brussels Central Station, C12 is a multidisciplinary platform launched by the Deep in House collective. A 1,000-capacity room for house and techno, plus art installations, exhibitions and guest nights billed as \"C12 Nite\".", site: "https://c12space.com/", instagram: "https://www.instagram.com/c12_bxl", match: ["c12"] },
  { slug: "circus-liverpool", name: "Circus", kind: "collectif", city: "Liverpool", country: "UK", since: 2002, desc: "Circus est la soirée house et techno lancée à Liverpool en septembre 2002 par le DJ et producteur Yousef, après la fin de sa résidence au Cream. Elle programme depuis ses propres dates dans les entrepôts et salles de la ville. En mai 2021 elle a accueilli les premières soirées sans distanciation du Royaume-Uni, dans le cadre du programme gouvernemental de tests.", descEn: "Circus is the house and techno night started in Liverpool in September 2002 by DJ and producer Yousef, after his Cream residency ended. It has run its own dates in the city's warehouses and venues ever since. In May 2021 it hosted the first restriction-free club nights in the UK as part of the government's Event Research Programme.", site: "https://www.circusclub.co.uk/", match: ["circus"], countries: ["UK"] },
  { slug: "club-de-jour", name: "Club de Jour", kind: "organisateur", city: "Nantes", country: "France", desc: "Club de Jour est le format diurne du Warehouse, à Nantes : une soirée de 19 h à minuit, six heures au lieu d'une nuit entière, pensée pour danser tôt et rentrer dormir. La direction artistique tourne autour de la house et de ses ramifications (disco, funk, électro hybride), avec des invités comme Kölsch, Guts, Bellaire ou Dimitri from Paris.", descEn: "Club de Jour is Warehouse Nantes' daytime format: a 7pm to midnight party, six hours instead of a full night, built for dancing early and still getting some sleep. The booking policy centres on house and its offshoots (disco, funk, hybrid electro) with guests such as Kölsch, Guts, Bellaire and Dimitri from Paris.", site: "https://www.warehouse-nantes.fr/concept/club-de-jour", instagram: "https://www.instagram.com/warehousenantes", match: ["club de jour"] },
  { slug: "colours", name: "Colours", kind: "organisateur", city: "Glasgow", country: "UK", desc: "Colours est le promoteur de dance music monté par Ricky Magowan, qui a programmé les grandes salles de Glasgow, des Arches au SWG3, et des scènes de festivals comme Gig On The Green. Il tient depuis 2002 son propre festival, Coloursfest, à la Braehead Arena de Renfrew, au bord de la Clyde.", descEn: "Colours is the dance music promoter built by Ricky Magowan, which has booked Glasgow's big rooms, from The Arches to SWG3, and festival stages such as Gig On The Green. Since 2002 it has run its own festival, Coloursfest, at Braehead Arena in Renfrew, on the banks of the Clyde.", match: ["colours"], countries: ["UK"] },
  { slug: "culture-box", name: "Culture Box", kind: "club", city: "Copenhagen", country: "Denmark", since: 2005, desc: "Culture Box est un club de Copenhague ouvert en 2005, que sa propre présentation décrit comme la plaque tournante de la scène électronique danoise. Il ouvre les vendredis et samedis de 22 h à 8 h et programme chaque semaine des artistes locaux et internationaux sur deux salles, la Black Box et la Red Box. Il porte aussi sa propre série de soirées, un podcast et un code de conduite affiché.", descEn: "Culture Box is a Copenhagen club that opened in 2005 and describes itself as the central hub of the Danish electronic music scene. It opens Fridays and Saturdays from 10pm to 8am and books local and international artists every week across two rooms, the Black Box and the Red Box. It also runs its own party series, a podcast and a published attitude code.", site: "https://www.culture-box.com/", instagram: "https://www.instagram.com/cultureboxdk", match: ["culture box"], venues: ["Culture Box"] },
  { slug: "dazed-muzic", name: "Dazed Muzic", kind: "organisateur", city: "Bristol", country: "UK", since: 2016, desc: "Dazed Muzic est une structure d'événements drum & bass et bass music fondée à Bristol en 2016, au départ une soirée hebdomadaire au Blue Mountain. Elle programme aujourd'hui des dates dans une dizaine de villes britanniques, et à Bristol au Thekla et au Lakota. Ses invités vont de Shy FX aux Kings of the Rollers.", descEn: "Dazed Muzic is a drum & bass and bass music events company founded in Bristol in 2016, starting as a weekly night at Blue Mountain. It now runs dates in around ten British cities, and in Bristol at Thekla and Lakota. Guests have ranged from Shy FX to Kings of the Rollers.", instagram: "https://www.instagram.com/dazedmuzic", match: ["dazed muzic"] },
  { slug: "detonate", name: "Detonate", kind: "organisateur", city: "Nottingham", country: "UK", since: 1999, desc: "Detonate est le promoteur drum & bass, jungle, garage et bass music de Nottingham, actif depuis 1999. Parti de soirées en sous-sol, il a programmé la plupart des salles de la ville, du Rock City au Stealth en passant par l'Unit 13 et The Brickworks, et organise son propre festival. Sa programmation mélange grosses têtes d'affiche et artistes émergents.", descEn: "Detonate is Nottingham's drum & bass, jungle, garage and bass music promoter, running since 1999. Starting with basement parties, it has booked most venues in the city, from Rock City and Stealth to Unit 13 and The Brickworks, and runs its own festival. Its billing mixes big headliners with emerging artists.", site: "https://detonate1.co.uk/", instagram: "https://www.instagram.com/detonateuk", match: ["detonate"] },
  { slug: "doof", name: "doof", kind: "label", city: "Dundee", country: "UK", desc: "doof est la marque et le label de la DJ et productrice écossaise Hannah Laing, originaire de Dundee, dont le nom vient du battement « doof doof » qu'elle joue. La marque a donné son propre festival, doof in the Park, au Camperdown Park de Dundee, dont la première édition en 2025 a réuni environ 15 000 personnes. En club, elle prend la forme de soirées hôtes dans les grandes salles britanniques.", descEn: "doof is the brand and label of Scottish DJ and producer Hannah Laing, from Dundee, named after the \"doof doof\" beat she plays. It has spawned its own festival, doof in the Park, at Camperdown Park in Dundee, whose first edition in 2025 drew around 15,000 people. In clubs it takes the form of hosted nights in large British venues.", match: ["doof"], countries: ["UK"] },
  { slug: "dour-festival", name: "Dour Festival", kind: "organisateur", city: "Dour", country: "Belgium", since: 1989, desc: "Fondé en 1989 par Carlo Di Antonio et Marc de Fays, le festival de Dour se tient chaque année en juillet sur la plaine de la Machine à Feu, dans le Hainaut. Porté par Dour Festival SA et l'asbl Go Go Go!, il réunit près de six scènes et fait une large place à la techno, à la house et à la drum & bass au milieu des musiques alternatives.", descEn: "Founded in 1989 by Carlo Di Antonio and Marc de Fays, Dour Festival takes place every July on the Plaine de la Machine à Feu, in Hainaut. Run by Dour Festival SA and the Go Go Go! non-profit, it spreads over some six stages and gives techno, house and drum & bass a large share of the bill alongside alternative music.", site: "https://www.dourfestival.eu/", instagram: "https://www.instagram.com/dourfestival", match: ["dour"] },
  { slug: "dvoid", name: "Dvoid", kind: "organisateur", city: "Liverpool", country: "UK", desc: "Dvoid est un promoteur de hard techno et de hardstyle basé à Liverpool, qui programme surtout le Hangar 34 et les salles dures de la ville. Il travaille beaucoup en plateau partagé avec les autres marques du circuit, Khaotic, Exhilaration ou Encore, et pousse des line-ups de six à huit noms.", descEn: "Dvoid is a hard techno and hardstyle promoter based in Liverpool, booking mainly Hangar 34 and the city's harder rooms. It works largely in joint billings with other brands on the circuit, Khaotic, Exhilaration or Encore, and puts up line ups of six to eight names.", match: ["dvoid"], countries: ["UK"] },
  { slug: "eastenderz", name: "Eastenderz", kind: "label", city: "London", country: "UK", since: 2014, desc: "Eastenderz est le label et la série de soirées fondés à Londres en 2014 par East End Dubs, d'abord comme une structure uniquement vinyle. La ligne est deep tech et minimal house, avec des touches de dub et de garage. Née de dates au fabric, au Studio 338 et à E1 London, la marque tourne aujourd'hui dans les clubs et festivals européens et tient une résidence à Ibiza.", descEn: "Eastenderz is the label and party series founded in London in 2014 by East End Dubs, at first a vinyl only imprint. The sound is deep tech and minimal house, with touches of dub and garage. Born of sold out nights at fabric, Studio 338 and E1 London, the brand now tours European clubs and festivals and holds an Ibiza residency.", site: "https://eastenderz.com/", match: ["eastenderz"], countries: ["UK"] },
  { slug: "elrow", name: "elrow", kind: "organisateur", city: "Barcelona", country: "Spain", since: 2010, desc: "elrow est la marque de soirées costumées et scénographiées fondée en 2010 par Cruz et Juan Arnau, à Barcelone. Elle appartient à la sixième génération d'une famille d'exploitants de Fraga, en Aragon, déjà à l'origine du club Florida 135 et du Monegros Desert Festival. Ses soirées tournent aujourd'hui d'Ibiza à Amsterdam.", descEn: "elrow is the costumed, heavily staged party brand founded in 2010 by Cruz and Juan Arnau in Barcelona. It belongs to the sixth generation of a promoter family from Fraga, in Aragon, already behind the Florida 135 club and the Monegros Desert Festival. Its parties now tour from Ibiza to Amsterdam.", site: "https://elrow.com/", instagram: "https://www.instagram.com/elrowofficial", match: ["elrow"] },
  { slug: "encrypted", name: "Encrypted", kind: "collectif", city: "Birmingham", country: "UK", desc: "Encrypted est un promoteur house, tech house et techno minimale de Birmingham, dont les soirées se tiennent au LAB11, l'entrepôt de Digbeth. La marque a fêté sa quatrième année en octobre 2026 avec Mason Collective, et programme aussi Bournemouth, où elle a pris ses quartiers au Vault.", descEn: "Encrypted is a house, tech house and minimal techno promoter from Birmingham, whose nights run at LAB11, the Digbeth warehouse. The brand marked its fourth year in October 2026 with Mason Collective, and also books Bournemouth, where it has made a second home at The Vault.", match: ["encrypted"] },
  { slug: "flashforward", name: "Flashforward", kind: "organisateur", city: "Charleroi", country: "Belgium", desc: "Flashforward est la nuit techno mensuelle du Rockerill, l'ancienne forge de Marchienne-au-Pont transformée en lieu culturel à Charleroi. Le rendez-vous assume un focus techno et house, fait tourner les résidents de la maison autour d'une tête d'affiche internationale, et attire un public venu de toute la Belgique et des pays limitrophes.", descEn: "Flashforward is Rockerill's monthly techno night, held in the former forge at Marchienne-au-Pont turned cultural venue in Charleroi. It has an openly techno and house focus, pairs the house residents with one international headliner, and draws a crowd from across Belgium and neighbouring countries.", site: "https://www.rockerill.com/", instagram: "https://www.instagram.com/rockerill", match: ["flashforward"] },
  { slug: "fly", name: "FLY", kind: "organisateur", city: "Edinburgh", country: "UK", since: 2013, desc: "FLY est une marque de soirées house et techno lancée à Édimbourg en 2013 par Tom Ketley, au départ un club night de 400 personnes. Elle a servi de tremplin aux résidences de Denis Sulta et Jasper James, et a créé en 2016 FLY Open Air, premier festival en plein air du centre d'Édimbourg, au Ross Bandstand des Princes Street Gardens. Elle programme aujourd'hui Édimbourg, Glasgow et Aberdeen.", descEn: "FLY is a house and techno brand started in Edinburgh in 2013 by Tom Ketley, at first a 400 capacity club night. It helped build the residencies of Denis Sulta and Jasper James, and in 2016 launched FLY Open Air, the first inner city open air festival in Edinburgh, at the Ross Bandstand in Princes Street Gardens. It now books Edinburgh, Glasgow and Aberdeen.", match: ["fly"] },
  { slug: "full-circle", name: "Full Circle", kind: "organisateur", city: "Antwerp", country: "Belgium", desc: "Full Circle est un festival de clubs à line-up 100 % belge : une seule journée, un seul billet, et une quarantaine de lieux d'une même ville ouverts en même temps, des clubs aux musées et maisons de la culture. Né à Anvers, il s'est doublé d'une édition gantoise, et annonce 150 artistes pour son affiche anversoise.", descEn: "Full Circle is a club festival with a 100% Belgian line-up: one day, one ticket, and around forty venues across a single city open at once, from clubs to museums and cultural centres. Born in Antwerp, it has since added a Ghent edition, and bills 150 artists for its Antwerp line-up.", site: "https://full-circle.be/", instagram: "https://www.instagram.com/fullcircle.festival", match: ["full circle"], countries: ["Belgium"] },
  { slug: "fury", name: "Fury", kind: "organisateur", city: "Barcelona", country: "Spain", desc: "Fury est la marque barcelonaise de hard techno, annoncée sous le mot d'ordre « Rave is Not a Crime » et produite par GMC Worldwide Productions. Elle tient son festival en plein air au Parc del Fòrum et des éditions en salle à Razzmatazz. La programmation est du hard techno et du hardcore, sans autre genre.", descEn: "Fury is Barcelona's hard techno brand, billed under the slogan \"Rave is Not a Crime\" and produced by GMC Worldwide Productions. It holds its open-air festival at Parc del Fòrum and indoor editions at Razzmatazz. The programme is hard techno and hardcore, and nothing else.", site: "https://parcdelforum.barcelona/es/agenda/fury-festival", match: ["fury"], countries: ["Spain"] },
  { slug: "fuse", name: "Fuse", kind: "club", city: "Brussels", country: "Belgium", since: 1994, desc: "Ouvert en avril 1994 rue Blaes, dans un ancien cinéma des Marolles, Fuse est le plus ancien club techno de Bruxelles et programme lui-même ses nuits sous les bannières « Fuse presents », « SESH » et « The Third Room ». La maison porte aussi une équipe de résidents et un label.", descEn: "Opened in April 1994 on Rue Blaes, in a former cinema in the Marolles district, Fuse is Brussels' oldest techno club and books its own nights under the \"Fuse presents\", \"SESH\" and \"The Third Room\" banners. It also runs a resident DJ team and a record label.", site: "https://www.fuse.be/", instagram: "https://www.instagram.com/fusebrussels", match: ["fuse presents", "fuse sesh", "fuse the third room"], venues: ["Fuse"] },
  { slug: "glitch-festival", name: "Glitch Festival", kind: "organisateur", city: "Rabat", country: "Malta", since: 2016, desc: "Glitch Festival est le rendez-vous maltais des musiques électroniques underground, dont la première édition date de 2016. Il se tient sur le site de Gianpula, près de Rabat, et ouvre par une soirée sous les fortifications du XVIe siècle de La Valette. Sa programmation va de la house et du disco à la techno, l'acid et l'electro.", descEn: "Glitch Festival is Malta's underground electronic music gathering, first held in 2016. It takes place at the Gianpula site near Rabat, and opens with a party beneath Valletta's 16th century fortifications. Its programme runs from house and disco to techno, acid and electro.", site: "https://www.glitchfestival.com/", instagram: "https://www.instagram.com/glitchfestival", match: ["glitch festival"] },
  { slug: "groovebox", name: "Groovebox", kind: "organisateur", city: "Nottingham", country: "UK", since: 2018, desc: "Groovebox est une marque house et tech house fondée à Nottingham en 2018, née de soirées de club dans les salles souterraines de la ville. Elle a pris ses quartiers au Binks Yard, où elle tient des journées en plein air, et a lancé le Groovebox Festival, une multi-scènes de 7 000 places. Elle porte aussi un label, Groovebox Recordings.", descEn: "Groovebox is a house and tech house brand founded in Nottingham in 2018, out of club nights in the city's underground venues. It has made a home at Binks Yard, where it runs open air day parties, and launched Groovebox Festival, a 7,000 capacity multi arena event. It also runs a label, Groovebox Recordings.", site: "https://groovebox.co.uk/", instagram: "https://www.instagram.com/wearegroovebox", match: ["groovebox"], countries: ["UK"] },
  { slug: "hadra", name: "Hadra", kind: "collectif", city: "Grenoble", country: "France", since: 2001, desc: "L'association Hadra a été fondée à Grenoble en 2001 par des passionnés de trance psychédélique, et a commencé dès 2002 par des soirées légales de 300 à 400 personnes dans la région grenobloise. Elle a inauguré son festival en 2005 à Chorges, installé depuis 2016 à Vieure dans l'Allier, et fait vivre en parallèle les labels Hadra Records et Altervision.", descEn: "The Hadra association was founded in Grenoble in 2001 by psytrance enthusiasts, and from 2002 ran legal parties of 300 to 400 people around Grenoble. It launched its festival in 2005 at Chorges, based at Vieure in the Allier since 2016, and also runs the Hadra Records and Altervision labels.", site: "https://www.hadra.net/", instagram: "https://www.instagram.com/hadra.official", match: ["hadra"] },
  { slug: "hardstylemoguls", name: "HardstyleMoguls", kind: "organisateur", city: "Liverpool", country: "UK", desc: "HardstyleMoguls est un promoteur de soirées hardstyle et rawstyle de Liverpool, qui programme l'Arts Club et le Club 051. Il fait venir des noms internationaux du style, de Da Tweekaz au projet The Ancients, sur des plateaux qui piochent aussi dans la hard techno.", descEn: "HardstyleMoguls is a hardstyle and rawstyle promoter from Liverpool, booking Arts Club and Club 051. It brings in international names of the style, from Da Tweekaz to The Ancients project, on bills that also reach into hard techno.", match: ["hardstylemoguls", "hardstyle moguls"], countries: ["UK"] },
  { slug: "hive", name: "Hive", kind: "club", city: "Zurich", country: "Switzerland", since: 2006, desc: "Le Hive est un club de musique électronique de Zurich, actif depuis 2006, qui présente aussi des expositions, des concerts et des lectures, et fait tourner son label Hive Audio. Sa programmation déborde le club avec Hive Air, la série en plein air dont le booking est tenu en interne, montée par exemple à la Halle 622.", descEn: "Hive is an electronic music club in Zurich, active since 2006, which also stages exhibitions, concerts and readings and runs its Hive Audio label. Its programme extends beyond the club with Hive Air, the open air series booked in house, staged for instance at Halle 622.", site: "https://hiveclub.ch/", instagram: "https://www.instagram.com/hive_club", match: ["hive air"], countries: ["Switzerland"], venues: ["Hive"] },
  { slug: "i-am-a-raver", name: "I Am A Raver", kind: "collectif", city: "Glasgow", country: "UK", desc: "I Am A Raver est une marque de soirées nostalgie montée par DJ Zitkus, qui a réuni autour d'elle les figures du dance écossais Gary McF, DJ Rankin, DJ Cammy et DJ Bad Boy comme résidents. Le format rassemble les hymnes de club d'hier et d'aujourd'hui sur une grosse production, et tourne en Écosse, en Irlande, en Angleterre et en résidence estivale à l'étranger.", descEn: "I Am A Raver is a nostalgia party brand built by DJ Zitkus, who recruited Scottish dance figures Gary McF, DJ Rankin, DJ Cammy and DJ Bad Boy as residents. The format puts past and present club anthems on a big production, and tours Scotland, Ireland, England and summer residencies abroad.", site: "https://iamaraver.co.uk/", match: ["i am a raver"] },
  { slug: "illusion-lorient", name: "Illusion", kind: "organisateur", city: "Lorient", country: "France", desc: "Illusion est la grande nuit hard music du pays de Lorient, présentée par Pandemic Events et Le Périscope au Parc des expositions de Lorient Bretagne Sud, à Lanester. L'affiche mélange techno, trance et hard music autour d'un décor à thème, et l'édition 2026 passe à deux scènes.", descEn: "Illusion is the big hard music night of the Lorient area, presented by Pandemic Events and Le Périscope at the Parc des Expositions Lorient Bretagne Sud in Lanester. The line-up mixes techno, trance and hard music around a themed set design, and the 2026 edition moves up to two stages.", site: "https://www.pandemic-events.com/illusion", match: ["illusion"], countries: ["France"], exclude: ["illusion saison"] },
  { slug: "into-the-madness", name: "Into The Madness", kind: "organisateur", city: "Vaihingen an der Enz", country: "Germany", desc: "Into The Madness est un festival hardstyle allemand qui se tient au Seepark Zülpich, porté par Into The Madness GmbH, société installée à Vaihingen an der Enz et dirigée par Benjamin Reichert et Tom van den Tillaer. La marque prolonge son édition d'été par une soirée d'avant-fête montée au Bootshaus de Cologne.", descEn: "Into The Madness is a German hardstyle festival held at Seepark Zülpich, run by Into The Madness GmbH, a company based in Vaihingen an der Enz and led by Benjamin Reichert and Tom van den Tillaer. The brand extends its summer edition with a pre party held at the Bootshaus in Cologne.", site: "https://www.intothemadness.de/", instagram: "https://www.instagram.com/intothemadnessfestival", match: ["into the madness"] },
  { slug: "jaeger", name: "Jæger", kind: "club", city: "Oslo", country: "Norway", desc: "Jæger est un club d'Oslo situé Grensen 9, sur deux étages plus une cour ouverte tard, avec des DJ tous les soirs de la semaine. Chaque soir porte son propre concept et son équipe de résidents, dont Frædag le vendredi, Mandagsklubben le lundi et M.A.D le mardi. Le club revendique une politique d'entrée ouverte, sans sélection à la porte.", descEn: "Jæger is a club in Oslo at Grensen 9, with two floors plus a late licence courtyard and DJs every night of the week. Each night has its own concept and resident crew, among them Frædag on Fridays, Mandagsklubben on Mondays and M.A.D on Tuesdays. The club states an open door policy, with no selection at the entrance.", site: "https://jaegeroslo.no/", instagram: "https://www.instagram.com/jaegeroslo", match: ["frædag", "fraedag", "jaeger"], venues: ["Jaeger"] },
  { slug: "jardin-electronique", name: "Le Jardin Électronique", kind: "organisateur", city: "Lille", country: "France", since: 2014, desc: "Créé en 2014 au Jardin des plantes de Lille, Le Jardin Électronique est devenu le plus gros festival de musiques électroniques du Nord et s'est installé en 2024 dans les 30 hectares du Parc naturel urbain de Lomme. Deux jours en plein air, une affiche répartie en tribus (Tech, Hard, Bass, Psy, et Mélodique depuis 2026), prolongés par un after en club.", descEn: "Created in 2014 at Lille's Jardin des Plantes, Le Jardin Électronique has become northern France's biggest electronic music festival and moved in 2024 to the 30 hectares of the Parc Naturel Urbain in Lomme. Two outdoor days, a line-up split into tribes (Tech, Hard, Bass, Psy, and Mélodique since 2026), followed by an afterparty in a club.", site: "https://www.jardinelectronique.com/", instagram: "https://www.instagram.com/lejardinelectronique", match: ["jardin electronique"], countries: ["France"] },
  { slug: "kaiku", name: "Kaiku", kind: "club", city: "Helsinki", country: "Finland", desc: "Kaiku est un club de musique électronique d'Helsinki, ouvert les vendredis et samedis, qui programme sa propre série Kaiku Presents à côté de soirées portées par des collectifs invités. Les affiches associent un nom international en tête de nuit et des DJ finlandais, sur deux espaces, avec une entrée gratuite avant 23 h.", descEn: "Kaiku is an electronic music club in Helsinki, open Fridays and Saturdays, running its own Kaiku Presents series alongside nights put on by guest collectives. Line-ups pair an international headliner with Finnish DJs across two rooms, with free entry before 11pm.", site: "https://clubkaiku.fi/", match: ["kaiku"], venues: ["Kaiku"] },
  { slug: "khaotic", name: "Khaotic", kind: "collectif", city: "Glasgow", country: "UK", desc: "Khaotic est un collectif écossais de hard techno, d'industriel et de hardstyle, parti de soirées glasvégiennes et devenu un nom de l'underground du pays. Sa ligne assume le format le plus dur du rave, gros son, visuels et plateaux à rallonge, et il tourne entre Glasgow, Édimbourg, Newcastle et Liverpool.", descEn: "Khaotic is a Scottish hard techno, industrial and hardstyle collective, grown out of Glasgow nights into a name in the country's underground. Its billing goes for the hardest end of rave, big sound, visuals and long line ups, and it tours between Glasgow, Edinburgh, Newcastle and Liverpool.", site: "https://www.khaotic.uk/", instagram: "https://www.instagram.com/khaotic.events", match: ["khaotic"], countries: ["UK"] },
  { slug: "kodz", name: "Kodz", kind: "club", city: "Englos", country: "France", since: 2025, desc: "Installé depuis le 5 septembre 2025 dans l'ancien Macumba du centre commercial d'Englos, aux portes de Lille, Kodz est présenté comme le plus grand club techno du nord de la France : 1 500 m2 pour un millier de personnes. Il signe lui-même ses nuits, seul ou en association avec d'autres collectifs, sous les intitulés « Kodz Presents » et « Kodz X ».", descEn: "Open since 5 September 2025 in the former Macumba at the Englos shopping centre, on the edge of Lille, Kodz bills itself as the largest techno club in northern France: 1,500 sq m for around a thousand people. It books its own nights, alone or with guest collectives, under the \"Kodz Presents\" and \"Kodz X\" banners.", instagram: "https://www.instagram.com/kodzclub", match: ["kodz"] },
  { slug: "kompass-klub", name: "Kompass Klub", kind: "club", city: "Ghent", country: "Belgium", since: 2016, desc: "Né d'un projet éphémère, Kompass Klub s'installe le 30 avril 2016 dans un entrepôt d'une zone industrielle du sud de Gand, puis Vliegtuiglaan depuis 2025. Trois salles, techno et house, et le titre de meilleur club belge aux Red Bull Elektropedia Awards en novembre 2018.", descEn: "Born as a pop-up project, Kompass Klub moved into a warehouse in an industrial park south of Ghent on 30 April 2016, and has been on Vliegtuiglaan since 2025. Three rooms, techno and house, and named best Belgian nightclub at the Red Bull Elektropedia Awards in November 2018.", site: "https://kompassklub.com/", instagram: "https://www.instagram.com/kompassklub", match: ["kompass"] },
  { slug: "kozzmozz", name: "Kozzmozz", kind: "organisateur", city: "Ghent", country: "Belgium", since: 1995, desc: "La première Kozzmozz a eu lieu le 23 septembre 1995 sur le bateau Josef K, dans le port de Gand : une fête entre amis destinée à défendre les DJs techno belges, dont le succès a imposé une suite. La marque a fait venir Secret Cinema, Rejuvination ou Adam Beyer pour leurs premières dates belges, puis a quitté le bateau pour l'ICC, le Vooruit et le Kuipke.", descEn: "The first Kozzmozz was held on 23 September 1995 on the boat Josef K in the port of Ghent: a party among friends meant to showcase Belgian techno DJs, whose success called for more editions. It brought Secret Cinema, Rejuvination and Adam Beyer to Belgium for the first time, then outgrew the boat and moved to the ICC, the Vooruit and the Kuipke velodrome.", site: "https://www.kozzmozz.com/", instagram: "https://www.instagram.com/into_the_kozzmozz", match: ["kozzmozz"] },
  { slug: "let-it-roll", name: "Let It Roll", kind: "organisateur", city: "Prague", country: "Czech Republic", desc: "Let It Roll est le festival tchèque de drum and bass, dont les premières éditions se tiennent en 2002 au club Mlejn, à Prague. Installé depuis 2015 sur l'ancien aérodrome militaire de Milovice, il a déménagé en 2025 au lac de Most, avec une scène flottante. Sa déclinaison d'hiver reste à Prague, en salle.", descEn: "Let It Roll is the Czech drum and bass festival, whose first editions were held in 2002 at the Mlejn club in Prague. Based since 2015 on the former military airfield at Milovice, it moved in 2025 to Lake Most, with a floating stage. Its winter edition stays indoors in Prague.", site: "https://letitroll.eu/", instagram: "https://www.instagram.com/letitrollfestival", match: ["let it roll"] },
  { slug: "liquicity", name: "Liquicity", kind: "label", city: "Amsterdam", country: "Netherlands", since: 2011, desc: "Liquicity est un label et un organisateur néerlandais de liquid drum and bass, né d'une chaîne YouTube ouverte en 2008 par Maris Goudzwaard et porté depuis 2011 avec Boudewijn Kustner et Mark van der Schoot, alias Maduk. La société d'événements est créée en janvier 2013 et la première soirée a lieu en mars de la même année à Ruigoord, près d'Amsterdam. La marque tient aujourd'hui un festival d'été, un Winterfestival et des dates en club à l'étranger.", descEn: "Liquicity is a Dutch liquid drum and bass label and promoter, grown out of a YouTube channel started in 2008 by Maris Goudzwaard and run since 2011 with Boudewijn Kustner and Mark van der Schoot, better known as Maduk. The events company was set up in January 2013 and the first party took place that March in Ruigoord, near Amsterdam. The brand now runs a summer festival, a Winterfestival and club dates abroad.", site: "https://liquicity.com/", instagram: "https://www.instagram.com/liquicity", match: ["liquicity"] },
  { slug: "loveland", name: "Loveland", kind: "organisateur", city: "Amsterdam", country: "Netherlands", since: 1995, desc: "Loveland organise des événements house et techno à Amsterdam depuis 1995, mention portée en toutes lettres par son propre site. Sa date principale est le Loveland Festival, deux jours au Sloterpark début août, complétée par le 909 Festival à l'Amsterdamse Bos, la journée BURST au Meerpark et une série de soirées pendant l'Amsterdam Dance Event. Chaque marque a son propre compte Instagram.", descEn: "Loveland has been putting on house and techno events in Amsterdam since 1995, a date its own site states in full. Its main event is Loveland Festival, two days in the Sloterpark in early August, alongside 909 Festival in the Amsterdamse Bos, the BURST day at Meerpark and a run of shows during Amsterdam Dance Event.", site: "https://www.loveland.nl/", instagram: "https://www.instagram.com/lovelandnl", match: ["loveland"], countries: ["Netherlands"] },
  { slug: "luminosity", name: "Luminosity", kind: "organisateur", city: "Zandvoort", country: "Netherlands", desc: "Luminosity Events est un organisateur néerlandais de soirées et de festivals trance. Sa date de référence est le Luminosity Beach Festival, sur la plage de Zandvoort, dont le site annonce les vingt ans en 2027, et il monte le reste de l'année des soirées à Amsterdam, dont une série pendant l'Amsterdam Dance Event.", descEn: "Luminosity Events is a Dutch promoter of trance parties and festivals. Its flagship date is Luminosity Beach Festival on the beach at Zandvoort, whose twentieth anniversary the site announces for 2027, and it runs club nights in Amsterdam the rest of the year, including a run during Amsterdam Dance Event.", site: "https://www.luminosity-events.nl/", instagram: "https://www.instagram.com/luminosity_events", match: ["luminosity"], countries: ["Netherlands"] },
  { slug: "magie-noire", name: "Magie Noire", kind: "collectif", city: "Montpellier", country: "France", desc: "Magie Noire est un collectif montpelliérain qui a fêté ses dix ans en 2026 et promène ses soirées électroniques dans toute la ville, de L'Antirouille au Tropisme, du Jardin des plantes au rooftop du Corum. Ses résidents, Luca Ruiz, Dask et Vincent Attalin, invitent régulièrement des noms de la scène internationale.", descEn: "Magie Noire is a Montpellier collective that celebrated ten years in 2026 and moves its electronic nights around the whole city, from L'Antirouille to Tropisme, from the Jardin des Plantes to the Corum rooftop. Its residents, Luca Ruiz, Dask and Vincent Attalin, regularly invite names from the international scene.", match: ["magie noire"], countries: ["France"] },
  { slug: "masters-of-hardcore", name: "Masters of Hardcore", kind: "organisateur", city: "Almere", country: "Netherlands", since: 1995, desc: "Masters of Hardcore est un événement hardcore néerlandais tenu pour la première fois le 1er juillet 1995 dans les halls sportifs d'Almere, sous le nom Doomsday - Masters of Hardcore. L'organisation à l'origine de la soirée, A&A events, est devenue Art of Dance en 2002 en s'associant à la Hemkade. La marque est aussi un label et exporte ses éditions hors des Pays-Bas depuis 2002.", descEn: "Masters of Hardcore is a Dutch hardcore event first held on 1 July 1995 in the sports halls of Almere, under the name Doomsday - Masters of Hardcore. A&A events, the organisation behind it, became Art of Dance in 2002 when it joined forces with the Hemkade. The brand is also a record label and has been staging editions outside the Netherlands since 2002.", site: "https://www.mastersofhardcore.com/", instagram: "https://www.instagram.com/mastersofhardcore", match: ["masters of hardcore"] },
  { slug: "modul8", name: "MODUL8", kind: "organisateur", city: "Birmingham", country: "UK", desc: "MODUL8 est une marque de soirées techno de Birmingham, qui assume le versant dur du style, peak time, acid, driving et hard techno. Sa règle affichée est de se passer de mise en jambes, « no warm ups, no fillers ». Elle programme le Tunnel Club et le SUKi10C et porte une résidence, The Dark Arch.", descEn: "MODUL8 is a Birmingham techno brand that goes for the hard end of the style, peak time, acid, driving and hard techno. Its stated rule is to do without a warm up, \"no warm ups, no fillers\". It books the Tunnel Club and SUKi10C and has a resident, The Dark Arch.", site: "https://modul8.uk/", instagram: "https://www.instagram.com/modul8_official", match: ["modul8"], countries: ["UK"] },
  { slug: "mondo-disko", name: "Mondo Disko", kind: "club", city: "Madrid", country: "Spain", since: 1999, desc: "Mondo Disko est le club de musique électronique de Madrid installé à la Sala But, calle Barceló 11. Ouvert depuis 1999, il programme techno et house à l'année. Il sort de ses murs avec Mondo Open Air, ses journées en plein air sur la Terraza Jowke d'Alcorcón, prolongées la nuit à la Sala But.", descEn: "Mondo Disko is Madrid's electronic music club, housed at Sala But on calle Barceló 11. Open since 1999, it programmes techno and house all year round. It steps outside with Mondo Open Air, its daytime sessions on the Terraza Jowke in Alcorcón, which carry on after dark at Sala But.", site: "https://www.mondodisko.es/", instagram: "https://www.instagram.com/mondo_disko", match: ["mondo disko", "mondo open air"] },
  { slug: "moondance", name: "Moondance", kind: "organisateur", city: "London", country: "UK", desc: "Moondance est l'une des institutions du rave londonien, sur une ligne jungle, drum & bass et hardcore tenue depuis plus de vingt ans. La marque a reçu Andy C, DJ Hype, Fabio & Grooverider et Shy FX, et a essaimé en festival et en week-ends. Elle organise chaque année une soirée de retrouvailles au KOKO, l'ancien Camden Palace.", descEn: "Moondance is one of the institutions of London rave, on a jungle, drum & bass and hardcore line held for more than two decades. The brand has hosted Andy C, DJ Hype, Fabio & Grooverider and Shy FX, and has spawned a festival and weekenders. Each year it runs a reunion night at KOKO, the former Camden Palace.", site: "https://www.moondanceevents.co.uk/", instagram: "https://www.instagram.com/moondanceeventsinfo", match: ["moondance"], countries: ["UK"] },
  { slug: "movement-entertainment", name: "Movement Entertainment", kind: "organisateur", city: "Turin", country: "Italy", desc: "Movement Entertainment est le producteur turinois du Kappa FuturFestival. Le festival est né en 2009 au Lingotto Fiere, puis a pris sa forme actuelle en 2013 en s'installant au Parco Dora, l'ancien site industriel Fiat et Michelin reconverti en parc. Il s'y tient depuis chaque été, de midi à minuit.", descEn: "Movement Entertainment is the Turin producer behind Kappa FuturFestival. The festival started in 2009 at Lingotto Fiere, then took its present shape in 2013 when it moved to Parco Dora, the former Fiat and Michelin industrial site turned park. It has been held there every summer since, from noon to midnight.", site: "https://www.kappafuturfestival.it/en", instagram: "https://www.instagram.com/futur_festival", match: ["kappa futurfestival"] },
  { slug: "nameless", name: "Nameless", kind: "organisateur", city: "Lecco", country: "Italy", since: 2013, desc: "Nameless est le festival lombard créé en 2013 par une équipe menée par Alberto Fumagalli, d'abord au centre sportif du Bione, à Lecco. Il a grandi à Barzio, en Valsassina, entre 2015 et 2019, avant de passer par Annone. Il revient au bord du lac de Côme pour son édition d'été et tient une Winter Edition à Barzio en février.", descEn: "Nameless is the Lombard festival created in 2013 by a team led by Alberto Fumagalli, first at the Bione sports centre in Lecco. It grew in Barzio, in Valsassina, between 2015 and 2019, before a spell in Annone. It is back by Lake Como for its summer edition and holds a Winter Edition in Barzio in February.", site: "https://www.namelessfestival.it/en", instagram: "https://www.instagram.com/namelessfestival", match: ["nameless"], countries: ["Italy"] },
  { slug: "neopop", name: "NEOPOP", kind: "organisateur", city: "Viana do Castelo", country: "Portugal", desc: "NEOPOP est le festival de musique électronique de Viana do Castelo, tenu au Forte de Santiago da Barra, au bord du Lima. Il est né sous le nom d'Antipop et l'a repris le temps de l'édition anniversaire d'août 2026, qui marque ses vingt ans. Sa programmation est dominée par la techno.", descEn: "NEOPOP is the electronic music festival of Viana do Castelo, held at the Forte de Santiago da Barra by the river Lima. It started out as Antipop and took that name back for the anniversary edition of August 2026, which marks twenty years. Its bill is dominated by techno.", site: "https://neopopfestival.net/", match: ["neopop"] },
  { slug: "nibirii", name: "Nibirii", kind: "organisateur", city: "Cologne", country: "Germany", desc: "Nibirii est un organisateur allemand basé à Cologne, qui tient un festival en plein air de trois jours au bord du Dürener Badesee et une série de dates en club le reste de l'année. Sa programmation va du drum and bass à la hard techno, et ses soirées club sont annoncées sous le nom Nibirii Clubshows.", descEn: "Nibirii is a German promoter based in Cologne, running a three day open air festival by the Dürener Badesee and a run of club dates the rest of the year. It books drum and bass through to hard techno, and its club nights are announced as Nibirii Clubshows.", site: "https://nibirii.com/", instagram: "https://www.instagram.com/nibirii", match: ["nibirii"] },
  { slug: "nightvision", name: "Nightvision", kind: "organisateur", city: "Edinburgh", country: "UK", since: 2014, desc: "Nightvision est la série de soirées électroniques lancée à Édimbourg en 2014, née du rapprochement des promoteurs house et techno de Musika et du collectif bass music Xplicit. Elle court de la mi-septembre au Nouvel An dans les salles de la ville, de La Belle Angele à l'Edinburgh Corn Exchange, et programme aussi Glasgow et Aberdeen.", descEn: "Nightvision is the electronic music series launched in Edinburgh in 2014, born of house and techno promoters Musika joining forces with bass music outfit Xplicit. It runs from mid September to New Year's Eve across the city's venues, from La Belle Angele to the Edinburgh Corn Exchange, and also books Glasgow and Aberdeen.", match: ["nightvision"] },
  { slug: "nitsa", name: "Nitsa", kind: "club", city: "Barcelona", country: "Spain", since: 1993, desc: "Nitsa est la nuit électronique de la Sala Apolo, à Barcelone. Née en 1993, elle s'installe dans la salle de l'avenue Paral·lel en septembre 1996 et y tient depuis ses sessions du vendredi et du samedi. Sa seconde salle, Astin, programme une affiche plus pointue dans La [2] de Apolo.", descEn: "Nitsa is the electronic club night of Sala Apolo in Barcelona. Born in 1993, it moved into the Paral·lel venue in September 1996 and has run its Friday and Saturday sessions there ever since. Its second room, Astin, programmes a sharper bill in La [2] de Apolo.", site: "https://www.nitsa.com/", instagram: "https://www.instagram.com/nitsa_club", match: ["nitsa", "astin"] },
  { slug: "nordstern", name: "Nordstern", kind: "club", city: "Basel", country: "Switzerland", desc: "Le Nordstern est un club bâlois installé sur le pont inférieur d'un ancien cargo fluvial amarré près de la Voltaplatz, réaménagé selon un principe de salle dans la salle pour l'acoustique, avec un système son signé L-Acoustics et WSDG. Il programme techno et house chaque week-end, et un second espace, le Club Futura, accueille les soirées plus petites.", descEn: "Nordstern is a Basel club set on the lower deck of a converted cargo ship moored near Voltaplatz, rebuilt on a room in a room principle for its acoustics, with a sound system designed with L-Acoustics and WSDG. It books techno and house every weekend, and a second space, Club Futura, hosts the smaller nights.", site: "https://nordstern.com/", instagram: "https://www.instagram.com/nordsternbasel", match: ["nordstern"], venues: ["Nordstern"] },
  { slug: "nuits-sonores", name: "Nuits sonores", kind: "organisateur", city: "Lyon", country: "France", since: 2003, desc: "Créé en 2003 par l'association lyonnaise Arty Farty, Nuits sonores est le grand rendez-vous des musiques électroniques et indépendantes de Lyon, cinq jours autour du week-end de l'Ascension. Le festival ne s'installe jamais durablement : il investit des friches industrielles et des espaces publics, dont les Grandes Locos depuis 2024.", descEn: "Founded in 2003 by the Lyon association Arty Farty, Nuits sonores is the city's landmark electronic and independent music festival, five days around the Ascension weekend. It never settles in one place: it takes over industrial wastelands and public spaces, including Les Grandes Locos since 2024.", site: "https://www.nuits-sonores.com/", instagram: "https://www.instagram.com/nuits_sonores", match: ["nuits sonores"] },
  { slug: "organik", name: "Organïk", kind: "collectif", city: "Paris", country: "France", since: 2018, desc: "Organïk est un collectif parisien lancé en 2018 avec une soirée d'ouverture en hangar au Blanc-Mesnil, qui réunit techno et micro house et revendique une organisation éco-responsable. Le format entrepôt reste son terrain de jeu, à Paris comme en tournée, du Warehouse de Nantes à la Halle de la Machine de Toulouse.", descEn: "Organïk is a Paris collective launched in 2018 with an opening night in a warehouse at Blanc-Mesnil, bringing techno and micro house together and claiming an eco-responsible way of putting on events. The warehouse format remains its home ground, in Paris and on tour, from Warehouse Nantes to the Halle de la Machine in Toulouse.", instagram: "https://www.instagram.com/organikparis", match: ["organik"], countries: ["France"] },
  { slug: "ozora-festival", name: "OZORA Festival", kind: "organisateur", city: "Dádpuszta", country: "Hungary", since: 2004, desc: "OZORA Festival est le rendez-vous hongrois de la psytrance, né en 2004 et tenu chaque été à Dádpuszta, près du village d'Ozora. Il s'est déroulé sans interruption depuis sa création, à l'exception des annulations de 2020 et 2021. Sa programmation mêle scènes électroniques et ateliers.", descEn: "OZORA Festival is Hungary's psytrance gathering, born in 2004 and held every summer at Dádpuszta, near the village of Ozora. It has run every year since it started, apart from the 2020 and 2021 cancellations. Its programme mixes electronic stages with workshops.", site: "https://ozorafestival.eu/", match: ["ozora"] },
  { slug: "peacock-society", name: "The Peacock Society", kind: "organisateur", city: "Paris", country: "France", since: 2013, desc: "Créée en 2013 par les producteurs parisiens We Love Art et Savoir-Faire, The Peacock Society est devenue l'une des principales manifestations électroniques de France, avec environ 25 000 festivaliers par édition. Elle se tient sur deux jours à l'Hippodrome de Paris-Vincennes et balaie la techno, la house et les lives.", descEn: "Created in 2013 by Paris promoters We Love Art and Savoir-Faire, The Peacock Society has become one of France's leading electronic music events, drawing around 25,000 people per edition. It runs over two days at the Hippodrome de Paris-Vincennes and covers techno, house and live sets.", site: "https://peacocksociety.fr/", instagram: "https://www.instagram.com/peacocksociety", match: ["peacock society"] },
  { slug: "positive-education", name: "Positive Education", kind: "collectif", city: "Saint-Étienne", country: "France", desc: "Positive Education est né de l'initiative de musiciens stéphanois et est devenu le rendez-vous électronique de référence de Saint-Étienne, chaque automne. La programmation fait cohabiter techno, house, drum & bass, ambient et expérimental, et le festival retrouve la Cité du design en 2026, sur trois scènes et une jauge volontairement réduite.", descEn: "Positive Education grew out of an initiative by musicians from Saint-Étienne and has become the city's reference electronic music event, held every autumn. The line-up mixes techno, house, drum & bass, ambient and experimental music, and in 2026 the festival returns to the Cité du design with three stages and a deliberately reduced capacity.", match: ["positive education"] },
  { slug: "pulsar-system", name: "Pulsar System", kind: "collectif", city: "Bordeaux", country: "France", since: 2024, desc: "Pulsar System est né en juillet 2024 à Bordeaux, monté par deux cousins, Kévin (Bertrance) et Paul (Wolverave), avec l'idée de rendre la techno accessible. Le collectif mélange house, trance, acid et techno sous l'intitulé Pulsar Mission, et se distingue autant par ses choix de lieux, de la Cour Mably au Hangar DS, que par ses affiches.", descEn: "Pulsar System started in July 2024 in Bordeaux, run by two cousins, Kévin (Bertrance) and Paul (Wolverave), with the idea of making techno approachable. The collective mixes house, trance, acid and techno under the Pulsar Mission banner, and stands out as much for its choice of venues, from the Cour Mably to Hangar DS, as for its line-ups.", instagram: "https://www.instagram.com/pulsar.system", match: ["pulsar mission", "pulsar system"], countries: ["France"] },
  { slug: "q-dance", name: "Q-dance", kind: "organisateur", city: "Landsmeer", country: "Netherlands", since: 1999, desc: "Q-dance est la société néerlandaise qui organise les grands rendez-vous des styles durs, hardstyle, hardcore et hard trance, dont Defqon.1, Qlimax et Dominator. Elle a été fondée en 1999 sous le nom Qlass Elite par un groupe d'amis de Landsmeer, au nord d'Amsterdam, avec Wouter Tavecchio parmi les fondateurs. Ses événements se reconnaissent au Q de leur nom, pour quality.", descEn: "Q-dance is the Dutch company behind the big harder styles events, hardstyle, hardcore and hard trance, among them Defqon.1, Qlimax and Dominator. It was founded in 1999 as Qlass Elite by a group of friends in Landsmeer, north of Amsterdam, with Wouter Tavecchio among the founders. Its events are recognisable by the Q in their name, which stands for quality.", site: "https://www.q-dance.com/", match: ["defqon", "dominator"], countries: ["Netherlands"] },
  { slug: "quarto-escuro", name: "1/4 Escuro", kind: "collectif", city: "Lisbon", country: "Portugal", desc: "1/4 Escuro est une marque de soirées techno de Lisbonne, qui tient une série au Ministerium Club et sort régulièrement dans d'autres lieux de la ville. Ses deux dates du catalogue sont coproduites avec Vault Sessions, marque amstellodamoise dont elle avait accueilli la première date portugaise à l'Armazém 8 Marvila en novembre 2024.", descEn: "1/4 Escuro is a Lisbon techno party brand, running a series at Ministerium Club and regularly stepping out to other venues in the city. Its two catalogue dates are co-produced with Vault Sessions, the Amsterdam brand whose first Portuguese date it hosted at Armazém 8 Marvila in November 2024.", site: "https://linktr.ee/umquartoescuro", instagram: "https://www.instagram.com/umquartoescuromusic", match: ["1/4 escuro"], countries: ["Portugal"] },
  { slug: "ritter-butzke", name: "Ritter Butzke", kind: "club", city: "Berlin", country: "Germany", since: 2007, desc: "Le Ritter Butzke est un club techno de Berlin-Kreuzberg, ouvert une première fois en 2007 dans deux anciens ateliers des usines Butzke, sans autorisation, puis rouvert légalement en octobre 2009 Ritterstraße 26, où il se trouve toujours. Il compte jusqu'à trois salles, tient une série Open Air, un label et une programmation qui sort de ses murs sous le nom Ritter Butzke on Tour.", descEn: "Ritter Butzke is a techno club in Berlin Kreuzberg, first opened in 2007 in two former workshops of the Butzke works, without permits, then reopened legally in October 2009 at Ritterstraße 26, where it still stands. It has up to three rooms, an Open Air series, a record label and a touring programme billed as Ritter Butzke on Tour.", site: "https://www.ritterbutzke.de/", instagram: "https://www.instagram.com/ritterbutzke.berlin", match: ["ritter butzke"], venues: ["Ritter Butzke"] },
  { slug: "rote-sonne", name: "Rote Sonne", kind: "club", city: "Munich", country: "Germany", since: 2005, desc: "La Rote Sonne est un club techno de Munich, ouvert le 5 août 2005 dans les caves réaménagées du Fortuna, au Maximiliansplatz, pour 300 à 400 personnes. Elle tient son nom du film de 1969 et compte parmi ses fondateurs Peter Wacha et Dorothea Zenker, venus de l'Ultraschall. Le club sort de ses murs pour son open air monté avec le Bahnwärter Thiel.", descEn: "Rote Sonne is a techno club in Munich, opened on 5 August 2005 in the rebuilt cellars of the former Fortuna on Maximiliansplatz, for 300 to 400 people. It takes its name from the 1969 film and counts Peter Wacha and Dorothea Zenker, both from Ultraschall, among its founders. The club steps outside its walls for its open air staged with Bahnwärter Thiel.", site: "https://rotesonne.com/", match: ["rote sonne"], countries: ["Germany"], venues: ["Rote Sonne"] },
  { slug: "rotterdam-rave", name: "Rotterdam Rave", kind: "organisateur", city: "Rotterdam", country: "Netherlands", since: 2013, desc: "Rotterdam Rave est le nom commun des soirées et festivals techno organisés à Rotterdam depuis 2013 par la société du même nom, fondée par Karim Soliman. La première édition s'est tenue au Perron devant un millier de personnes, avant que les soirées ne s'installent au Maassilo. Un festival en plein air a été ajouté en 2016.", descEn: "Rotterdam Rave is the collective name of the techno parties and festivals held in Rotterdam since 2013 by the company of the same name, founded by Karim Soliman. The first edition took place at Perron in front of about a thousand people, before the parties settled at the Maassilo. An open air festival was added in 2016.", site: "https://www.rotterdamrave.com/", match: ["rotterdam rave"] },
  { slug: "second-speed", name: "Second Speed", kind: "organisateur", city: "Liverpool", country: "UK", desc: "Second Speed est un promoteur britannique qui monte des soirées techno sur le modèle des clubs européens, d'abord à Liverpool puis dans le nord de l'Angleterre. Il porte son propre festival, Accelerate, au Gateshead International Stadium près de Newcastle. Sa programmation va de la techno rapide à la hard techno, avec des noms comme Funk Tribu, blk. ou Vieze Asbak.", descEn: "Second Speed is a British promoter putting on techno nights on the European club model, first in Liverpool then across the north of England. It runs its own festival, Accelerate, at Gateshead International Stadium near Newcastle. Its billing goes from fast techno to hard techno, with names such as Funk Tribu, blk. and Vieze Asbak.", match: ["second speed"], countries: ["UK"] },
  { slug: "shangri-la-cardiff", name: "Shangri-La", kind: "collectif", city: "Cardiff", country: "UK", since: 2011, desc: "Shangri-La est la soirée house et techno créée à Cardiff en avril 2011 par Nick Saunders et James Cromwell, alors étudiants à Cardiff Met, d'abord au GLAM Nightclub de Greyfriars Road. Elle s'est depuis installée au Depot, la salle de 2 100 places que Nick Saunders a lui-même montée, et y reçoit des têtes d'affiche house et techno.", descEn: "Shangri-La is the house and techno night started in Cardiff in April 2011 by Nick Saunders and James Cromwell, then Cardiff Met students, first at what was GLAM Nightclub on Greyfriars Road. It has since moved to Depot, the 2,100 capacity venue Saunders went on to found, where it books house and techno headliners.", match: ["shangri-la"] },
  { slug: "sonar", name: "Sónar", kind: "organisateur", city: "Barcelona", country: "Spain", since: 1994, desc: "Sónar est le festival de musiques avancées et d'arts numériques de Barcelone, produit par la société Advanced Music. La première édition s'est tenue du 2 au 4 juin 1994, entre le CCCB le jour et la Sala Apolo la nuit. La manifestation se partage aujourd'hui entre Fira Montjuïc pour Sónar by Day et Fira Gran Via pour Sónar by Night.", descEn: "Sónar is Barcelona's festival of advanced music and digital art, produced by Advanced Music. The first edition ran from 2 to 4 June 1994, split between the CCCB by day and Sala Apolo by night. The event now spreads across Fira Montjuïc for Sónar by Day and Fira Gran Via for Sónar by Night.", site: "https://sonar.es/en", instagram: "https://www.instagram.com/sonarfestival", match: ["sonar"] },
  { slug: "techno-is-our-life", name: "Techno Is Our Life", kind: "collectif", city: "Montpellier", country: "France", since: 2020, desc: "Techno Is Our Life est une association montpelliéraine née en 2020, qui se définit comme un collectif techno et rave. Elle produit ses soirées sous l'intitulé Acidnight, entre mentalcore, acidcore et tribe, et les emmène hors de Montpellier, à Rouen, à Pau et à Paris. Le collectif met en avant sa production (laser, lumière, V-jing, décors) autant que son affiche.", descEn: "Techno Is Our Life is a Montpellier association founded in 2020 that describes itself as a techno and rave collective. It runs its nights under the Acidnight banner, between mentalcore, acidcore and tribe, and takes them beyond Montpellier to Rouen, Pau and Paris. The collective puts as much emphasis on production (lasers, lighting, VJing, decor) as on the line-up.", site: "https://technoisourlife.com/", instagram: "https://www.instagram.com/techno_is_our_life", match: ["techno is our life"], countries: ["France"] },
  { slug: "teletech", name: "Teletech", kind: "collectif", city: "Manchester", country: "UK", since: 2017, desc: "Teletech est un collectif techno né à Manchester en 2017, monté par Tom Shenton et Anton Stevens à partir de soirées étudiantes du quartier de Fallowfield. La marque organise aujourd'hui ses propres dates dans une dizaine de villes britanniques et son festival, en plus de scènes accueillies sur de gros festivals européens.", descEn: "Teletech is a techno collective founded in Manchester in 2017 by Tom Shenton and Anton Stevens, out of student house parties in Fallowfield. The brand now runs its own dates across a dozen British cities plus its own festival, alongside stages hosted at large European festivals.", site: "https://www.teletech.events/", instagram: "https://www.instagram.com/teletechuk", match: ["teletech"] },
  { slug: "the-holy-rave", name: "The Holy Rave", kind: "collectif", city: "Dijon", country: "France", desc: "The Holy Rave est un collectif qui numérote ses soirées et les fait tourner de club en club, du Bal'tazar de Dijon au Ground de Luxembourg, au Teasing Club de Besançon et à Metz. Le principe est d'inviter des clubs et des labels locaux à porter une nuit dans une salle underground, plutôt que de réimporter la même affiche partout.", descEn: "The Holy Rave is a collective that numbers its nights and moves them from club to club, from Bal'tazar in Dijon to Ground in Luxembourg, Le Teasing Club in Besançon and on to Metz. The idea is to invite local clubs and labels to host a night in an underground room, rather than shipping the same line-up everywhere.", instagram: "https://www.instagram.com/theholyrave", match: ["the holy rave"], countries: ["France", "Luxembourg"] },
  { slug: "the-warehouse-project", name: "The Warehouse Project", kind: "organisateur", city: "Manchester", country: "UK", since: 2006, desc: "The Warehouse Project est la saison de soirées lancée à Manchester en 2006 par Sacha Lord et Sam Kandel, deux anciens du Sankeys. Contrairement à un club, elle ne tourne pas toute l'année : chaque saison court de septembre au Nouvel An. Depuis 2019 elle se tient à Depot Mayfield, ancien dépôt ferroviaire et centre de tri postal reconverti.", descEn: "The Warehouse Project is the seasonal club series started in Manchester in 2006 by Sacha Lord and Sam Kandel, both Sankeys veterans. Unlike a club it does not run all year: each season goes from September to New Year's Day. Since 2019 it has been staged at Depot Mayfield, a former railway yard and Royal Mail distribution centre.", site: "https://www.thewarehouseproject.com/", instagram: "https://www.instagram.com/whp_mcr", match: ["the warehouse project"], countries: ["UK"], venues: ["Depot Mayfield"] },
  { slug: "toffler", name: "Toffler", kind: "club", city: "Rotterdam", country: "Netherlands", since: 2011, desc: "Toffler est un club house et techno de Rotterdam ouvert en 2011, installé dans un ancien tunnel piétonnier sous le Weena, connu pour sa cabine et son système son montés sur vérins hydrauliques qui agrandissent la salle au fil de la nuit. Le club porte aussi le Toffler Festival, lancé en 2015, seul festival tenu par une boîte de nuit de la ville.", descEn: "Toffler is a house and techno club in Rotterdam that opened in 2011, set in a former pedestrian tunnel under the Weena and known for its hydraulic booth and sound system, which enlarge the room as the night goes on. The club also runs Toffler Festival, launched in 2015, the only festival put on by a Rotterdam nightclub.", site: "https://www.toffler.nl/", instagram: "https://www.instagram.com/tofflerrotterdam", match: ["toffler"], venues: ["Toffler"] },
  { slug: "tomorrowland", name: "Tomorrowland", kind: "organisateur", city: "Boom", country: "Belgium", since: 2005, desc: "Première édition le 14 août 2005 au domaine provincial De Schorre, à Boom : Tomorrowland est devenu le plus grand rendez-vous de musique électronique de Belgique, détenu à 100 % par les frères Manu et Michiel Beers via leur société We Are One World. La marque a ouvert une déclinaison hivernale en 2019, Tomorrowland Winter, à l'Alpe d'Huez.", descEn: "First held on 14 August 2005 at the De Schorre provincial estate in Boom, Tomorrowland has become Belgium's largest electronic music event, owned outright by brothers Manu and Michiel Beers through their company We Are One World. The brand opened a winter edition in 2019, Tomorrowland Winter, at Alpe d'Huez.", site: "https://www.tomorrowland.com/", instagram: "https://www.instagram.com/tomorrowland", match: ["tomorrowland"], countries: ["Belgium", "France"] },
  { slug: "trancecoda", name: "Trancecoda", kind: "organisateur", city: "Nottingham", country: "UK", desc: "Trancecoda est un promoteur de soirées trance qui tourne entre plusieurs villes anglaises, de Nottingham à Brighton en passant par Plymouth et Coalville. Sa programmation couvre tout l'éventail du style, de l'uplifting et du progressif au tech et au hard trance, avec des têtes d'affiche comme Paul van Dyk, Ferry Corsten ou Aly & Fila. La structure porte aussi un label.", descEn: "Trancecoda is a trance promoter touring several English cities, from Nottingham to Brighton by way of Plymouth and Coalville. Its billing spans the whole style, from uplifting and progressive to tech and hard trance, with headliners such as Paul van Dyk, Ferry Corsten and Aly & Fila. It also runs a label.", site: "https://trancecoda.com/", instagram: "https://www.instagram.com/trancecodaevents", match: ["trancecoda"], countries: ["UK"] },
  { slug: "tresor", name: "Tresor", kind: "club", city: "Berlin", country: "Germany", since: 1991, desc: "Tresor a ouvert dans une ancienne salle des coffres de la Leipziger Strasse le 13 mars 1991 et le label Tresor Records est né la même année. Le club a porté très tôt le dialogue entre Berlin et Detroit, en programmant Juan Atkins, Underground Resistance et Drexciya. Il occupe aujourd'hui une ancienne centrale thermique et fait tourner sa marque hors les murs, notamment sous le nom Tresor.West.", descEn: "Tresor opened in a former bank vault on Leipziger Strasse on 13 March 1991, and the Tresor Records label was founded the same year. The club drove the early dialogue between Berlin and Detroit, booking Juan Atkins, Underground Resistance and Drexciya. It now occupies a former power plant and takes its brand on the road, notably under the Tresor.West name.", site: "https://www.tresorberlin.com/", instagram: "https://www.instagram.com/tresorberlin", match: ["tresor klubnacht", "tresor meets", "tresor invites", "tresor records"], venues: ["Tresor"] },
  { slug: "under-events", name: "UNDER", kind: "collectif", city: "La Teste-de-Buch", country: "France", desc: "UNDER n'est pas tout à fait bordelais : Enzo et Antoine ont lancé le projet sur le bassin d'Arcachon, où il mêle soirées techno et marque de vêtements. Parti des bars du territoire, notamment à La Teste-de-Buch, le collectif invite depuis des références de la scène techno bordelaise, dont Marée Basse, et monte des formats entrepôt.", descEn: "UNDER is not quite a Bordeaux outfit: Enzo and Antoine started the project on the Arcachon basin, where it combines techno parties with a clothing label. Having begun in local bars, notably in La Teste-de-Buch, the collective now invites names from the Bordeaux techno scene, among them Marée Basse, and puts on warehouse-format nights.", instagram: "https://www.instagram.com/under__events", match: ["under events"], countries: ["France"] },
  { slug: "unsound", name: "Unsound", kind: "organisateur", city: "Kraków", country: "Poland", since: 2003, desc: "Unsound est le festival de musiques expérimentales et électroniques de Cracovie, lancé en 2003 dans les caves de la ville. Il est porté par la fondation Tone, avec Mat Schulz comme directeur artistique et cofondateur. Son édition 2026, « Soft Power », se tient à Varsovie puis à Cracovie.", descEn: "Unsound is the experimental and electronic music festival of Kraków, launched in 2003 in the city's cellar bars. It is run by the Tone foundation, with Mat Schulz as artistic director and co-founder. Its 2026 edition, \"Soft Power\", runs in Warsaw and then in Kraków.", site: "https://www.unsound.pl/en", instagram: "https://instagram.com/unsoundfestival", match: ["unsound"] },
  { slug: "untold", name: "UNTOLD", kind: "organisateur", city: "Cluj-Napoca", country: "Romania", since: 2015, desc: "UNTOLD est le festival de Cluj-Napoca créé en 2015, l'année où la ville était capitale européenne de la jeunesse. Il se tient à la Cluj Arena et dans les espaces qui l'entourent, et sa première édition a réuni plus de 240 000 personnes en quatre jours. Il est porté par la fédération SHARE Cluj-Napoca.", descEn: "UNTOLD is the Cluj-Napoca festival created in 2015, the year the city was European Youth Capital. It is held at Cluj Arena and the grounds around it, and its first edition drew more than 240,000 people over four days. It is run by the SHARE Cluj-Napoca federation.", site: "https://untold.com/", instagram: "https://www.instagram.com/untoldfestival", match: ["untold"] },
  { slug: "verknipt", name: "Verknipt", kind: "organisateur", city: "Utrecht", country: "Netherlands", desc: "Verknipt est un organisateur néerlandais de soirées et de festivals hard techno. Son festival annuel se tient début juin sur le terrain du Strijkviertel à Utrecht, et la marque exporte ses dates hors des Pays-Bas, à Berlin, Oberhausen et Zurich. Elle programme aussi une édition ADE à l'AFAS Live et un réveillon au Klokgebouw d'Eindhoven.", descEn: "Verknipt is a Dutch promoter of hard techno parties and festivals. Its annual festival runs in early June on the Strijkviertel grounds in Utrecht, and the brand takes its dates abroad to Berlin, Oberhausen and Zurich. It also runs an ADE edition at AFAS Live and a New Year's night at the Klokgebouw in Eindhoven.", site: "https://www.verknipt.org/", match: ["verknipt"] },
  { slug: "vision-milano", name: "Vision", kind: "organisateur", city: "Milan", country: "Italy", desc: "Vision est la série milanaise de plein air tenue à l'ex Macello, viale Molise 62, l'ancien abattoir de la ville. La saison 2026 court du 1er mai au 5 septembre, de 17 h à minuit, et c'est la troisième et dernière sur ce site, dont la requalification urbaine reprend après l'été. La billetterie et les aftershows passent par l'Amnesia Milano, et quelques dates se tiennent à la Fabrique.", descEn: "Vision is the Milanese open-air series held at the ex Macello, viale Molise 62, the city's former slaughterhouse. The 2026 season runs from 1 May to 5 September, 5pm to midnight, and is the third and last on that site, whose urban redevelopment resumes after the summer. Ticketing and aftershows go through Amnesia Milano, and a few dates are held at Fabrique.", site: "https://amnesiamilano.com/", match: ["vision"], countries: ["Italy"] },
  { slug: "we-are-whse", name: "We Are WHSE", kind: "organisateur", city: "Derby", country: "UK", desc: "We Are WHSE est la série de soirées montée par l'équipe du Forbidden Forest Festival pour l'ULTRA, l'entrepôt de 3 500 places ouvert dans une zone industrielle de Derby. La programmation couvre la house, la tech house et la drum & bass, en saisons numérotées. Sa deuxième saison, SZN002, est en cours.", descEn: "We Are WHSE is the club series set up by the Forbidden Forest Festival team for ULTRA, the 3,500 capacity warehouse opened on a Derby industrial estate. It books house, tech house and drum & bass, programmed in numbered seasons. Its second season, SZN002, is under way.", site: "https://www.wearewhse.com/", instagram: "https://www.instagram.com/weare_whse", match: ["we are whse"] },
  { slug: "wolf-city", name: "Wolf City", kind: "organisateur", city: "Paris", country: "France", since: 2024, desc: "Wolf City est le concept de soirées hardcore créé en 2024 par le DJ français Hysta, dont la première édition s'est tenue à Paris avec Angerfist, Furyan et Korsakoff. Chaque date est construite autour de la scène locale qui l'accueille, sur tout l'éventail de la hard music, hardstyle, hardcore, frenchcore et uptempo, et la marque tourne désormais bien au-delà de la France.", descEn: "Wolf City is the hardcore party concept created in 2024 by French DJ Hysta, whose first edition was held in Paris with Angerfist, Furyan and Korsakoff. Each date is built around the local scene hosting it, across the full range of hard music (hardstyle, hardcore, frenchcore and uptempo), and the brand now tours well beyond France.", site: "https://hysta.dj/wolf-city/", instagram: "https://www.instagram.com/hysta.dj", match: ["wolf city"], countries: ["France"] },
  { slug: "wonderful-days", name: "Wonderful Days", kind: "organisateur", city: "Cologne", country: "Germany", desc: "Wonderful Days est une série de soirées allemandes sous-titrée The Classic Rave Festival, consacrée au rave, à la techno et au hardstyle des origines. Elle tourne de salle en salle plutôt que de rester sur un site, du Bootshaus de Cologne à la Nachtfabrik de Reutlingen en passant par le Neuraum de Munich et E-Dry à Geldern. Ses bureaux sont à Cologne.", descEn: "Wonderful Days is a German party series subtitled The Classic Rave Festival, devoted to early rave, techno and hardstyle. It tours from venue to venue rather than staying on one site, from the Bootshaus in Cologne to the Nachtfabrik in Reutlingen by way of Neuraum in Munich and E-Dry in Geldern. Its offices are in Cologne.", site: "https://wonderfuldays-festival.com/", instagram: "https://www.instagram.com/wonderfuldays_festival", match: ["wonderful days"] },
  { slug: "worried-about-henry", name: "Worried About Henry", kind: "organisateur", city: "London", country: "UK", since: 2014, desc: "Worried About Henry, abrégé WAH, est un promoteur de soirées drum & bass, bass et garage fondé en 2014, qui programme aujourd'hui plus de vingt villes britanniques. Il tient chaque année une nuit du Warehouse Project à Manchester, des dates à Drumsheds et son propre festival de jour, WAH In The City, dans les Royal Docks de Londres. Il programme aussi des scènes de festivals comme Parklife.", descEn: "Worried About Henry, known as WAH, is a drum & bass, bass and garage promoter founded in 2014, now booking more than twenty British cities. It hosts a Warehouse Project night in Manchester every year, dates at Drumsheds and its own day festival, WAH In The City, in London's Royal Docks. It also programmes festival stages such as Parklife.", site: "https://worriedabouthenry.com/", instagram: "https://www.instagram.com/worriedabouthenry", match: ["worried about henry", "wah"], countries: ["UK"] },
];
/* PROMOTERS:end */

const words = (s: string): string[] => slugify(s).split("-").filter(Boolean);

/** `needle` apparaît-il comme suite de mots consécutifs dans `hay` ? */
function runOf(hay: string[], needle: string[]): boolean {
  if (needle.length === 0 || needle.length > hay.length) return false;
  for (let i = 0; i + needle.length <= hay.length; i++) {
    let ok = true;
    for (let j = 0; j < needle.length; j++) {
      if (hay[i + j] !== needle[j]) {
        ok = false;
        break;
      }
    }
    if (ok) return true;
  }
  return false;
}

/* Un seul passage sur le catalogue, et les libellés de `match` découpés une seule
   fois : la table est lue par toutes les fiches au build, la reconstruire à chaque
   appel coûterait des millions de comparaisons pour la même réponse. */
const INDEX = (() => {
  const needles = RAW.map((p) => ({
    p,
    match: p.match.map(words),
    venues: new Set((p.venues ?? []).map(slugify)),
    countries: p.countries ? new Set(p.countries) : null,
    exclude: (p.exclude ?? []).map(words),
  }));
  const byPromoter = new Map<string, RaveEvent[]>();
  const byEvent = new Map<number, Promoter[]>();
  for (const e of EVENTS) {
    const title = words(e.title);
    const venue = slugify(e.venue);
    for (const n of needles) {
      if (n.countries && !n.countries.has(e.country)) continue;
      const hit = n.match.some((m) => runOf(title, m)) || n.venues.has(venue);
      if (!hit) continue;
      if (n.exclude.some((m) => runOf(title, m))) continue;
      const at = byPromoter.get(n.p.slug);
      if (at) at.push(e);
      else byPromoter.set(n.p.slug, [e]);
      const ev = byEvent.get(e.id);
      if (ev) ev.push(n.p);
      else byEvent.set(e.id, [n.p]);
    }
  }
  return { byPromoter, byEvent };
})();

/**
 * Combien de salles, de villes et de titres distincts la marque touche.
 *
 * **Sa propre salle ne compte que pour une**, quelle que soit la façon dont le
 * catalogue l'écrit : le Tresor de Berlin apparaît en « Tresor » et en « Tresor /
 * Globus », deux slugs pour un seul bâtiment, ce qui suffisait à faire croire à un
 * programme réparti et à ouvrir une page en concurrence avec `/lieux/tresor`. Une
 * salle nommée d'après la marque est la salle de la marque, pas un débordement.
 */
const spread = (slug: string, events: RaveEvent[]) => ({
  venues: new Set(events.map((e) => {
    const v = slugify(e.venue);
    return v.startsWith(slug) ? slug : v;
  })).size,
  cities: new Set(events.map((e) => slugify(e.city))).size,
  /* Le titre porte le festival et pas l'édition (règle de contenu du projet), donc
     deux éditions de Sónar comptent pour un seul titre : c'est exactement ce qu'il
     faut compter ici, un organisateur qui ne tient qu'un festival est déjà décrit
     par `/festival/{slug}`. */
  titles: new Set(events.map((e) => slugify(e.title))).size,
});

/**
 * Une marque a une page quand son programme déborde d'une seule page existante.
 *
 * Deux dates au minimum, et deux conditions cumulées :
 *
 * - **au moins deux salles ou deux villes**, sinon `/lieux/{slug}` décrit déjà la
 *   même chose, avec l'adresse et la carte en plus. La salle qui porte le nom de la
 *   marque ne compte que pour une, voir `spread()` ;
 * - **au moins deux titres distincts**, sinon c'est `/festival/{slug}` qui décrit
 *   déjà la même chose. Un organisateur qui ne tient qu'un festival n'ajoute rien,
 *   il double la fiche du festival sur sa propre requête.
 *
 * Le calcul se fait au build, donc une marque entre d'elle-même le jour où un lot
 * lui apporte une date ailleurs, sans rien à basculer à la main.
 */
export function isPageworthy(slug: string, events: RaveEvent[]): boolean {
  if (events.length < 2) return false;
  const s = spread(slug, events);
  return (s.venues >= 2 || s.cities >= 2) && s.titles >= 2;
}

function build(): Promoter[] {
  return RAW.filter((p) => isPageworthy(p.slug, INDEX.byPromoter.get(p.slug) ?? [])).sort((a, b) =>
    a.name.localeCompare(b.name),
  );
}

export const PROMOTERS: Promoter[] = build();

const BY_SLUG = new Map(PROMOTERS.map((p) => [p.slug, p]));
export const promoterBySlug = (s: string): Promoter | undefined => BY_SLUG.get(s);

/** Les dates de la marque, à venir d'abord. */
export const eventsForPromoter = (slug: string): RaveEvent[] =>
  upcomingFirst(INDEX.byPromoter.get(slug) ?? []);

/**
 * Les marques qui programment cet événement.
 *
 * Filtré sur `PROMOTERS` et pas sur `RAW` : une marque écartée par `build()` n'a pas
 * de page, et poser son nom en lien donnerait un 404 sur une fiche indexée. Même
 * règle que `hasArtistPage()` pour un nom ajouté à un line-up.
 */
export const promotersForEvent = (e: RaveEvent): Promoter[] =>
  (INDEX.byEvent.get(e.id) ?? []).filter((p) => BY_SLUG.has(p.slug));

/** Ce que la marque programme, pondéré, voir `rankGenres()` (lib/data.ts). */
export const promoterGenres = (slug: string): string[] => rankGenres(INDEX.byPromoter.get(slug) ?? []);

/** Les villes où la marque pose ses dates, la plus servie d'abord. */
export function promoterCities(slug: string): { city: string; count: number }[] {
  const tally = new Map<string, number>();
  for (const e of INDEX.byPromoter.get(slug) ?? []) tally.set(e.city, (tally.get(e.city) ?? 0) + 1);
  return [...tally.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([city, count]) => ({ city, count }));
}

/** Les salles où la marque programme, la plus servie d'abord. */
export function promoterVenues(slug: string): { name: string; slug: string; count: number }[] {
  const tally = new Map<string, { name: string; count: number }>();
  for (const e of INDEX.byPromoter.get(slug) ?? []) {
    const k = slugify(e.venue);
    if (!k) continue;
    const at = tally.get(k);
    if (at) at.count++;
    else tally.set(k, { name: e.venue, count: 1 });
  }
  return [...tally.entries()]
    .sort((a, b) => b[1].count - a[1].count || a[1].name.localeCompare(b[1].name))
    .map(([slug, v]) => ({ slug, name: v.name, count: v.count }));
}

/**
 * Les habitués de la marque : les noms qui reviennent le plus sur ses affiches.
 *
 * Même seuil et même raison que `venueRegulars()` : sur deux dates, tout le monde
 * serait « régulier », donc un nom vu une seule fois ne compte pas. Rendu vide plutôt
 * que faux.
 */
export function promoterRegulars(slug: string, n: number, min = 2): { name: string; count: number }[] {
  const tally = new Map<string, number>();
  for (const e of INDEX.byPromoter.get(slug) ?? []) {
    for (const raw of e.lineup) {
      const name = raw.trim();
      if (name) tally.set(name, (tally.get(name) ?? 0) + 1);
    }
  }
  return [...tally.entries()]
    .filter(([, c]) => c >= min)
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, n)
    .map(([name, count]) => ({ name, count }));
}

/** Le nombre de dates à venir, pour un compteur de pilule qui ne promet rien de faux. */
export const promoterUpcoming = (slug: string, today?: string): RaveEvent[] =>
  upcoming(INDEX.byPromoter.get(slug) ?? [], today);

/**
 * L'image de partage d'une fiche d'organisateur.
 *
 * Contrairement à une fiche de salle, l'affiche d'une soirée est ici **le sujet** :
 * c'est l'artwork de la marque, pas l'annonce d'un événement étranger à la page. On
 * prend donc la première date qui porte une vraie photo ou une affiche, à venir de
 * préférence, et rien plutôt qu'un dégradé sans information.
 */
export function promoterOgImage(slug: string): string | null {
  for (const e of eventsForPromoter(slug)) {
    if (PHOTOS[e.id]) return imageUrl(e);
  }
  return null;
}
